"""Stable analysis artifact contracts and schema versions."""

from .intelligence import INTELLIGENCE_BASE_FIELDS

EXTRACTION_SCHEMA_VERSION = "brand-extraction-v4"


CSV_FIELD_SCHEMAS = {
    "brand_mentions_extracted": [
        "query_id",
        "repeat_index",
        "input_query",
        "brand_name_raw",
        "brand_name_canonical",
        "brand_type",
        "sov_eligible",
        "role",
        "is_recommended",
        "rank_position",
        "sentiment",
        "mention_context",
        "confidence",
        "evidence",
        "canonical_hint",
    ],
    "brand_canonical_map": ["brand_name_raw", "brand_name_canonical"],
    "brand_summary": [
        "sov_rank",
        "brand_name_canonical",
        "raw_names",
        "responses_mentioned",
        "response_mention_count",
        "mention_rate",
        "response_mention_rate",
        "query_coverage",
        "query_coverage_count",
        "query_coverage_rate",
        "query_macro_mention_rate",
        "sov_event_share",
        "sov_response_share",
        "recommended_count",
        "recommended_rate",
        "recommended_rate_when_mentioned",
        "recommended_rate_over_success",
        "rank_observed_count",
        "rank_observed_rate",
        "avg_rank_position",
        "top3_rate",
        "positive_rate",
        "neutral_rate",
        "negative_rate",
        "sentiment_unknown_rate",
        "sentiment_observed_rate",
        "avg_confidence",
        "is_target_brand",
        "target_brand_detected",
        "target_rank_by_sov",
        "target_sov_gap_to_leader",
        "target_sov_gap_to_top3_avg",
    ],
    "brand_by_query": [
        "query_id",
        "query",
        "brand_name_canonical",
        "responses_mentioned",
        "mention_rate_within_query",
        "recommended_responses",
        "recommended_rate_within_query",
        "recommended_rate_when_mentioned_within_query",
        "recommended_rate_over_success_within_query",
    ],
    "query_stability": [
        "query_id",
        "query",
        "successful_repeats",
        "expected_repeats",
        "sample_sufficient",
        "brand_set_jaccard_avg",
        "unique_brand_sets",
        "top_brands",
    ],
    "source_entity_mentions": [
        "query_id",
        "repeat_index",
        "input_query",
        "brand_name_raw",
        "brand_name_canonical",
        "brand_type",
        "sov_eligible",
        "role",
        "mention_context",
        "evidence",
    ],
    "source_domains": [
        "domain",
        "parsed_source_occurrences",
        "distinct_source_url_count",
        "response_coverage",
        "response_coverage_rate",
        "query_coverage",
        "query_coverage_rate",
        "avg_source_order",
        "best_source_order",
        "top_urls",
    ],
    "source_urls": ["url", "domain", "title", "parsed_source_occurrences"],
    "source_by_query": [
        "query_id",
        "domain",
        "repeat_coverage",
        "repeat_coverage_rate",
        "parsed_source_occurrences",
        "distinct_source_url_count",
        "avg_source_order",
        "top_urls",
    ],
    "quality_summary": [
        "job_id",
        "sample_mode",
        "conclusion_strength",
        "partial_sample",
        "planned_units",
        "analysis_record_count",
        "stats_record_count",
        "missing_unit_count",
        "latest_failed_unit_count",
        "web_search_quality_flag_count",
        "source_quality_flag_count",
        "extraction_error_record_count",
        "extraction_error_rate",
    ],
    "attempt_facts": [
        "job_id",
        "query_id",
        "repeat_index",
        "latest_status",
        "completed_at",
        "valid_attempt",
        "stats_included",
        "web_search_requirement_status",
        "web_search_evidence",
        "source_parse_status",
        "request_hash",
        "attempt_id",
    ],
    "query_facts": [
        "job_id",
        "query_id",
        "query",
        "planned_attempts",
        "latest_terminal_attempts",
        "completed_attempts",
        "valid_attempts",
        "stats_included_attempts",
        "latest_failed_attempts",
        "sample_completeness",
        "usable_sample_rate",
        "query_metadata_json",
    ],
    "brand_attempt_facts": [
        "job_id",
        "query_id",
        "repeat_index",
        "attempt_id",
        "brand_name_canonical",
        "brand_name_raw",
        "is_target_brand",
        "sov_eligible",
        "is_recommended",
        "recommendation_type",
        "recommendation_strength",
        "rank_position",
        "sentiment",
        "confidence",
        "evidence",
        "role",
        "condition",
        "audience",
        "use_case",
        "budget_level",
        "tradeoff",
        "traceability_status",
        "stats_included",
    ],
    "brand_trends": [
        "job_id",
        "target_brand",
        "industry",
        "market",
        "model",
        "web_search_limit",
        "extraction_schema_version",
        "expected_queries",
        "expected_repeats",
        "sample_mode",
        "query_set_hash",
        "conclusion_strength",
        "extraction_error_rate",
        "comparability_key",
        "partial_sample",
        "brand_name_canonical",
        "is_target_brand",
        "sov_rank",
        "sov_event_share",
        "sov_response_share",
        "response_mention_rate",
        "query_coverage_rate",
        "recommended_rate",
        "recommended_rate_when_mentioned",
        "recommended_rate_over_success",
        "rank_observed_rate",
        "sentiment_unknown_rate",
        "avg_rank_position",
        "positive_rate",
        "neutral_rate",
        "negative_rate",
        "target_sov_gap_to_leader",
        "target_sov_gap_to_top3_avg",
        "success_record_count",
    ],
}
CSV_FIELD_SCHEMAS.update(INTELLIGENCE_BASE_FIELDS)
